### ISSUE TITLE
sklearn imports are being deprecated - issues with pip installer

### ISSUE THREAD

**Issue by warner121** [mbhynes/skelo#6]
Hey thanks for sharing this lovely package. I'm having some issues with the sklearn imports as of yesterday, 1st December 2022, due to the implementation of their brownouts. Please see: https://pypi.org/project/sklearn/ for more info.

**Comment by mbhynes** [comment]
Hi Daniel, thanks for reporting this!
This looks like an easy fix over here in the setup.py file.
I'll carve out some time to patch it 👍

**Comment by mbhynes** [comment]
Version bump available:
https://pypi.org/project/skelo/0.1.5/

@warner121 This works over on my end, please let me know if you run into any issues:
![image](https://user-images.githubusercontent.com/10452129/205337812-ed6ebdf4-f166-48fc-bb9d-8a4f93bfc66f.png)

**Comment by warner121** [comment]
Looks good from my side too. Thanks for fixing so quickly :)
